<template>
  <div class="container">
    <br>
    <h1 class="display-3">Total sales</h1>
    <br><br>
    <b-table outlined :items="financialData"></b-table>
    <b-button variant="primary" class="float-right">
      <router-link tag="span" to="booking">Make another booking</router-link>
    </b-button>
    <br>
  </div>
</template>

<script>
export default {
  computed: {
    financialData() {
      const storeData = this.$store.getters.getTotalCost;
      const data = [
        {
          type: 'Revenue',
          amount: storeData.revenue,
          description: 'Total revenue generated by bookings today'
        },
        {
          type: 'Service tax',
          amount: storeData.tax,
          description: '14% service tax paid to the government'
        },
        {
          type: 'Swachh Bharat Cess',
          amount: storeData.sbCess,
          description: '0.5% Swachh Bharat Cess paid to the government'
        },
        {
          type: 'Krishi Kalyan Cess',
          amount: storeData.kkCess,
          description: '0.5% Krishi Kalyan Cess paid to the government'
        }
      ];
      return data;
    }
  }
};
</script>
