import { mount, createLocalVue } from '@vue/test-utils';
import BootstrapVue from 'bootstrap-vue';
import Vuex from 'vuex';
import SalesVue from '@/views/Sales.vue';

const localVue = createLocalVue();
localVue.use(Vuex);
localVue.use(BootstrapVue);

let store, totalCost, wrapper;
const getters = {
  getTotalCost: () => totalCost
};

describe('Sales', () => {
  beforeEach(() => {
    totalCost = {
      revenue: 1000,
      tax: 100,
      sbCess: 10,
      kkCess: 10,
    };
    store = new Vuex.Store({
      getters
    });
    wrapper = mount(SalesVue, {
      store,
      localVue,
      stubs: ['router-link'],
      computed: {
        financialData() {
          const storeData = getters.getTotalCost();
          return [
            {
              type: 'Revenue',
              amount: storeData.revenue,
              description: 'Total revenue generated by bookings today'
            },
            {
              type: 'Service tax',
              amount: storeData.tax,
              description: '14% service tax paid to the government'
            },
            {
              type: 'Swachh Bharat Cess',
              amount: storeData.sbCess,
              description: '0.5% Swachh Bharat Cess paid to the government'
            },
            {
              type: 'Krishi Kalyan Cess',
              amount: storeData.kkCess,
              description: '0.5% Krishi Kalyan Cess paid to the government'
            }
          ];
        }
      }
    });
  });

  it('is a Vue instance', () => {
    expect(wrapper.isVueInstance()).toBeTruthy();
  });

  it('gets sales data from store', () => {
    expect(getters.getTotalCost()).toBe(totalCost);
  });

  it('prints sales data', () => {
    expect(wrapper.text().indexOf(totalCost.revenue) >= 0).toBe(true);
  });
});